// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    public partial class ElkTacoRecipe
    {
        partial void ModsPreInitialize()
        {
            var product = new Recipe(
                "ElkTaco",
                Localizer.DoStr("Elk Taco"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(ScrapMeatItem), 10, typeof(AdvancedCookingSkill)),
                    new IngredientElement(typeof(TortillaItem), 2, typeof(AdvancedCookingSkill)),
                    new IngredientElement(typeof(WildMixItem), 1, typeof(AdvancedCookingSkill)),
                    new IngredientElement(typeof(TomatoSauceItem), 1, typeof(AdvancedCookingSkill)),
                },
                new GarbageOutput[] {},
                new CraftingElement<ElkTacoItem>()
            );

            this.Recipes = new List<Recipe> { product };
        }
    }
}
