// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from FoodTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System.Collections.Generic;
    using Eco.Core.Items;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    public partial class TastyTropicalPizzaRecipe
    {
        partial void ModsPreInitialize()
        {
            var product = new Recipe(
                "TastyTropicalPizza",
                Localizer.DoStr("Tasty Tropical Pizza"),
                new IngredientElement[]
                {
                    new IngredientElement(typeof(LeavenedDoughItem), 2, typeof(AdvancedBakingSkill)),
                    new IngredientElement(typeof(RawBaconItem), 1, typeof(AdvancedBakingSkill)),
                    new IngredientElement(typeof(PineappleItem), 1, typeof(AdvancedBakingSkill)),
                    new IngredientElement(typeof(SunCheeseItem), 2, typeof(AdvancedBakingSkill)),
                    new IngredientElement(typeof(TomatoSauceItem), 2, typeof(AdvancedBakingSkill)),
                },
                new GarbageOutput[] {},
                new CraftingElement<TastyTropicalPizzaItem>()
            );

            this.Recipes = new List<Recipe> { product };
        }
    }
}
