// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
	using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Gameplay.Garbage;

    [Serialized]
    [LocDisplayName("Herbivore Lure")]
    [SalvageCost(typeof(FoodScrap), 0.4f)]
    [Weight(300)]
    [Tag("Salad")]
    [Ecopedia("Food", "Cooking", createAsSubPage: true)]
    public partial class HerbivoreLureItem : FoodItem
    {
        public LocString DisplayDescription    => Localizer.DoStr("Works as a lure for animals that eat plants.");
        
        public override float Calories                  => 800;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 8, Fat = 4, Protein = 2, Vitamins = 12};
		public override float BaseShelfLife            => (float)TimeUtil.HoursToSeconds(72);
        //protected override int BaseShelfLife => (int)TimeUtil.HoursToSeconds(72);
    }

}
