// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
	using Eco.Shared.Utils;
    using Eco.Shared.Time;
    using Eco.Core.Items;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    [Serialized]
    [LocDisplayName("Herbivore Ration")]
    [SalvageCost(typeof(FoodScrap), 0.4f)]
    [Weight(300)]
    [Tag("Salad")]
    [Ecopedia("Food", "Cooking", createAsSubPage: true)]
    public partial class HerbivoreRationItem : FoodItem
    {
        public virtual LocString DisplayDescription    => Localizer.DoStr("Works as a Ration for animals that eat plants.");
        
        public override float Calories                  => 800;
        public override Nutrients Nutrition             => new Nutrients() { Carbs = 14, Protein = 5, Vitamins = 7};
		public override float BaseShelfLife            => (float)TimeUtil.HoursToSeconds(72);
    }

}
