// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from ItemTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;

    [RequiresSkill(typeof(CuttingEdgeCookingSkill), 0)]
    public partial class HydrocolloidsRecipe : RecipeFamily
    {
        public HydrocolloidsRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "Hydrocolloids", 
                displayName: Localizer.DoStr("Hydrocolloids"),

                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(RiceFlourItem), 200, typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingLavishResourcesTalent)),
                },

                items: new List<CraftingElement>
                {
                    new CraftingElement<HydrocolloidsItem>(1)
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 3; 
            
            this.LaborInCalories = CreateLaborInCaloriesValue(200, typeof(CuttingEdgeCookingSkill));

            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(HydrocolloidsRecipe), start: 2.0f, skillType: typeof(CuttingEdgeCookingSkill), typeof(CuttingEdgeCookingFocusedSpeedTalent), typeof(CuttingEdgeCookingParallelSpeedTalent));

            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Hydrocolloids"), recipeType: typeof(HydrocolloidsRecipe));
            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(LaboratoryObject), recipeFamily: this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();


    }
}