// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from BenefitTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Mods.TechTree;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;

    /// <summary>
    /// <para>Server side talent definition for "CocktailHands".</para>
    /// </summary>
    public partial class CocktailHandsTalent : Talent
    {
        public override bool Base => true;
        public override Type TalentType { get { return typeof(CraftingTalent); } }
    }

    [Serialized]
    [LocDisplayName("Cocktail Hands")]
    [LocDescription("Increase craft speed of all advanced mixology recipes by 100%.")]
    public partial class CocktailHandsTalentGroup : TalentGroup
    {
        public CocktailHandsTalentGroup()
        {
            Talents = new Type[]
            {
                typeof(AdvancedMixologyCocktailHandsTalent),
            };
            this.OwningSkill = typeof(AdvancedMixologySkill);
            this.Level = 6;
        }
    }

    [Serialized]
    public partial class AdvancedMixologyCocktailHandsTalent : CocktailHandsTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(CocktailHandsTalentGroup); } }
    }
}