// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from BenefitTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Mods.TechTree;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;

    public partial class MixologyDesertExpertTalent : Talent
    {
        public override bool Base => true;
        public override Type TalentType { get { return typeof(CraftingTalent); } }
    }

    [Serialized]
    [LocDisplayName("Tropical & Desert Master")]
    [LocDescription("15% cost reduction for Desert and Tropical Smoothie.")]
    public partial class MixologyDesertExpertTalentGroup : TalentGroup
    {
        public MixologyDesertExpertTalentGroup()
        {
            Talents = new Type[]
            {
                typeof(MixologySkillDesertExpertTalent),
            };
            this.OwningSkill = typeof(MixologySkill);
            this.Level = 6;
        }
    }

    [Serialized]
    public partial class MixologySkillDesertExpertTalent : MixologyDesertExpertTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(MixologyDesertExpertTalentGroup); } }
    }
}
