// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from BenefitTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Mods.TechTree;
    using Eco.Shared.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;

    public partial class MixologyFocusedWorkflowTalent : Talent
    {
        public override bool Base => true;
        public override Type TalentType { get { return typeof(CraftingTalent); } }
    }

    [Serialized]
    [LocDisplayName("Juice Master")]
    [LocDescription("Reduces craft cost of Mixology by 15% and increases juices production by 1.")]
    public partial class MixologyFocusedWorkflowTalentGroup : TalentGroup
    {
        public MixologyFocusedWorkflowTalentGroup()
        {
            Talents = new Type[]
            {
                typeof(MixologySkillFocusedWorkflowTalent),
            };
            this.OwningSkill = typeof(MixologySkill);
            this.Level = 3;
        }
    }

    [Serialized]
    public partial class MixologySkillFocusedWorkflowTalent : MixologyFocusedWorkflowTalent
    {
        public override bool Base { get { return false; } }
        public override Type TalentGroupType { get { return typeof(MixologyFocusedWorkflowTalentGroup); } }
    }
}
