// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated /> 

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Shared.SharedTypes;
    using Eco.World.Water;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
	using Eco.Core.Plugins.Interfaces;
    using Eco.Gameplay.Garbage;


    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    public partial class DryTailingsLv2 : RecipeFamily
    {
        public DryTailingsLv2()
        {
            var recipe = new Recipe();
                recipe.Init(
                name: "DryTailingsLv2",
                displayName: Localizer.DoStr("Dry Tailings Lv2"),
                ingredients: new List<IngredientElement>
                {
					new IngredientElement(typeof(WetTailingsItem), 3, typeof(RecyclingSkill)), 
                },
                garbages: new List<GarbageOutput>
                {
                },
                items: new List<CraftingElement>
                {
					new CraftingElement<TailingsItem>(8),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 2.0f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(10, typeof(RecyclingSkill)); 
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(DryTailingsLv2), start: 0.25f, skillType: typeof(RecyclingSkill));     
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Dry Tailings Lv2"), recipeType: typeof(DryTailingsLv2));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(IncineratorObject), recipeFamily: this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
