// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated /> 

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Shared.SharedTypes;
    using Eco.World.Water;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    public partial class Tailings2Sand : RecipeFamily
    {
        public Tailings2Sand()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "TailingsToSand",
                displayName: Localizer.DoStr("Tailings To Sand"),
                ingredients: new List<IngredientElement>
                {
					new IngredientElement(typeof(DirtItem), 1, typeof(PotterySkill)), 
                },
                garbages: new List<GarbageOutput>
                {
                },
                items: new List<CraftingElement>
                {
					new CraftingElement<SandItem>(1),
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 0.5f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(5, typeof(PotterySkill)); 
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(Tailings2Sand), start: 0.125f, skillType: typeof(PotterySkill));
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Tailings to Sand"), recipeType:typeof(Tailings2Sand));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(tableType: typeof(KilnObject), recipeFamily: this);
        }
        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }
}
