// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from PluginModuleTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Core.Items;
    using Eco.World;
    using Eco.World.Blocks;
    using Eco.Gameplay.Pipes;
    using Eco.Core.Controller;
    using Eco.Gameplay.Items.Recipes;
    using Eco.Gameplay.Garbage;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>

    [RequiresSkill(typeof(AdvancedMixologySkill), 7)]
    [Ecopedia("Upgrade Modules", "Specialty Upgrades", subPageName: "Advanced Mixology Upgrade Item")]
    public partial class AdvancedMixologyUpgradeRecipe : RecipeFamily
    {
        public AdvancedMixologyUpgradeRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "AdvancedMixologyUpgrade",  //noloc
                displayName: Localizer.DoStr("Advanced Mixology Upgrade"),
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(AdvancedUpgradeItem), 1, true),
                },
                garbages: new List<GarbageOutput>
                {
                },
                items: new List<CraftingElement>
                {
                    new CraftingElement<AdvancedMixologyUpgradeItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 4;

            this.LaborInCalories = CreateLaborInCaloriesValue(6000, typeof(AdvancedMixologySkill));
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(AdvancedMixologyUpgradeRecipe), start: 15, skillType: typeof(AdvancedMixologySkill));

            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Advanced Mixology Upgrade"), recipeType: typeof(AdvancedMixologyUpgradeRecipe));
            this.ModsPostInitialize();

            CraftingComponent.AddRecipe(tableType: typeof(AdvancedMixologyTableObject), recipeFamily: this);
        }

        partial void ModsPreInitialize();
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Advanced Mixology Upgrade")]
    [LocDescription("Advanced Upgrade that greatly increases efficiency when crafting Mixology recipes.")]
    [Weight(1)]
    [Ecopedia("Upgrade Modules", "Specialty Upgrades", createAsSubPage: true)]
    [Tag("Upgrade")]
    [Tag("SpecialtyModule")]
    public partial class AdvancedMixologyUpgradeItem : EfficiencyModule
    {
        public AdvancedMixologyUpgradeItem() : base(
            ModuleTypes.ResourceEfficiency | ModuleTypes.SpeedEfficiency,
            0.75f + 0.05f,
            typeof(AdvancedMixologySkill),
            0.75f
        ) { }
    }
}
